name: travel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  shared_preferences: ^2.5.3
  http: ^1.2.1
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  equatable: ^2.0.7
  firebase_database: ^11.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/todo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/todoimg.png

  android_12:
    image: assets/todoimg.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
